Fixes hydration warnings on the homepage
hiveboardgame/hive pull request #313
Opened 2024-07-30 05:47 UTC by IongIer

Gets rid of hydration warnings on the homepage caused by trying to load a leptix radio group from an unopened Modal.

2024-07-30 15:42 UTC, PenguinWithATie commented
Just to comment, leptix 0.3 will implement a few floating and modal components, It will be worth trying to leverage this once it comes out

2024-07-30 15:45 UTC, PenguinWithATie approved these changes

2024-07-31 06:24 UTC, klautcomputing requested changes

2024-07-31 06:24 UTC, klautcomputing commented on apis/src/components/atoms/direct_challenge_button.rs
> +            <Show when=open>
Can this `Show` move inside?

2024-07-31 06:48 UTC, klautcomputing approved these changes
My name is klautcomputing and I approve this PR.

2024-07-31 07:28 UTC, merged