add history controls to chat, add analysis button to history
hiveboardgame/hive pull request #319
Opened 2024-08-07 21:29 UTC by PenguinWithATie

- add analysis button to history
- add history controls to chat
- moving from history to chat (also chat to history) now maintains history turn, moving to game goes to the last.

Note: removed the mutable reference in `GameStateSignal::show_history_turn` since its needed to use inside the callback and also its not required to update the signal, might be worth changing other functions of this type in a similar way, to make life simpler

2024-08-12 14:46 UTC, klautcomputing approved these changes
Works! We can fix the nitpick or just merge it as is. I will happily deploy once you have merged it.

2024-08-14 06:47 UTC, klautcomputing approved these changes

2024-08-14 07:35 UTC, IongIer requested changes
This is severely broken. There's a bunch of runtime errors if you try to open chat in the mobile view. + a lot of yellow warnings in the browser console. Not sure I will have time today to investigate where the problem really comes from.....I just checked main, we have some of the errors there as well, so the problem is not completely here but the changes in this stopped the mobile chat from working at least.

2024-08-20 07:32 UTC, IongIer approved these changes

2024-08-20 13:20 UTC, merged