working on filtering
hiveboardgame/hive pull request #344
Opened 2024-10-04 22:04 UTC by kd2718

this is my first MR writing rust, so there are a few things i am not sure about. I am not yet finished.

2024-10-22 16:15 UTC, kd2718 commented
![image](https://github.com/user-attachments/assets/5d4952c3-2b4d-4fc1-a7a1-5857470904e6)

![image](https://github.com/user-attachments/assets/a379ad30-8b67-4932-b28f-bdc33b17b733)


Added filter buttons to clean up tournament view.

2024-10-23 07:04 UTC, klautcomputing requested changes
I have mainly style changes, your Rust looks fine to me.

@IongIer can you take a look at the leptos specifics?

2024-10-23 07:04 UTC, klautcomputing commented on shared_types/src/lib.rs
> +pub use tournament_sort_order::TournamentSortOrder;
Please set up your IDE to include a newline at the end of the file.

2024-10-23 07:29 UTC, IongIer commented on apis/src/pages/tournaments.rs
> +    let filter = create_rw_signal(TournamentFilter::Status(TournamentStatus::NotStarted));
these create...functions are getting deprecated. Use RwSignal::new() instead.

2024-10-24 06:26 UTC, IongIer commented on apis/src/pages/tournaments.rs
> +                            "Completed"
I would rename this to Finished to keep it consistent with the player profile

2024-10-24 19:12 UTC, kd2718 commented
Just a note: running `cargo clippy --fix --all-features && leptosfmt apis -q && cargo fmt` changes a ton of files. Maybe we should have a PR to just sync everything

2024-10-29 07:53 UTC, IongIer approved these changes

2024-10-29 18:06 UTC, klautcomputing approved these changes

2024-11-08 21:10 UTC, merged